# Generated by Django 4.1.7 on 2023-03-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('badgeName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('badgeIcon', models.ImageField(upload_to=None)),
                ('badgeDescirption', models.CharField(max_length=500)),
                ('badgeUnlocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt_List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=50)),
                ('promptGenre', models.CharField(max_length=30)),
                ('alreadyUsed', models.BooleanField(default=False)),
                ('previousWinner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=320)),
                ('profilePicture', models.ImageField(upload_to=None)),
                ('favouriteDraw', models.ImageField(upload_to=None)),
                ('badgesEarned', models.CharField(max_length=30)),
                ('darkMode', models.BooleanField(default=False)),
                ('averageRating', models.FloatField()),
                ('currentStreak', models.IntegerField(default=0)),
                ('maxStreak', models.IntegerField(default=0)),
                ('totalStars', models.IntegerField(default=0)),
                ('friends', models.CharField(max_length=30)),
                ('friendRequests', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=423)),
            ],
        ),
        migrations.CreateModel(
            name='User_memories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('timeCompleted', models.TimeField()),
                ('difficulty', models.CharField(max_length=10)),
                ('avgRating', models.FloatField(default=0.0)),
                ('TimeTaken', models.TimeField()),
                ('prompt', models.CharField(max_length=50)),
                ('drawing', models.ImageField(upload_to='uploads/drawings')),
            ],
        ),
    ]
