# Generated by Django 4.1.7 on 2023-03-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawfulApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_memories',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
