# Generated by Django 4.1.7 on 2023-04-24 10:14

from django.db import migrations, models
import drawfulApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawfulApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_memories',
            name='drawing',
            field=models.ImageField(upload_to=drawfulApp.models.generateFilename),
        ),
    ]
