# Generated by Django 4.2 on 2023-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawfulApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_memories',
            name='username',
            field=models.CharField(default='defaultUser', max_length=30),
            preserve_default=False,
        ),
    ]
