# Generated by Django 4.1.7 on 2023-03-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawfulApp', '0002_alter_user_memories_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_memories',
            name='drawing',
            field=models.ImageField(upload_to='uploads/drawings'),
        ),
    ]
