services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=drawful
      - POSTGRES_USER=drawful
      - POSTGRES_PASSWORD=drawful
  web:
    build: /home/gitlab-runner/builds/ZTttgQvU/0/team-projects-2022-23/team40-22/
    command: python3 ./drawful/manage.py runserver 127.0.0.1:80
    volumes:
      - /home/gitlab-runner/builds/ZTttgQvU/0/team-projects-2022-23/team40-22/drawful
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=drawful
      - POSTGRES_USER=drawful
      - POSTGRES_PASSWORD=drawful
    depends_on:
      - db