services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=drawful
      - POSTGRES_USER=drawful
      - POSTGRES_PASSWORD=drawful
      - POSTGRES_HOST=localhost
  web:
    build: /home/gitlab-runner/builds/ZTttgQvU/0/team-projects-2022-23/team40-22/
    volumes:
      - /home/gitlab-runner/builds/ZTttgQvU/0/team-projects-2022-23/team40-22/drawful
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=drawful
      - POSTGRES_USER=drawful
      - POSTGRES_PASSWORD=drawful
      - POSTGRES_HOST=db:5432
    links:
      - "db:database"
    depends_on:
      - db
  #app:
    #container_name: docker_react_app
    #image: docker-react-image
    #volumes:
      #- ".:/app"
      #- "/app/node_modules"
    #ports:
      #- "3000:3000"
    #depends_on:
      #- web
