services:
  db:
    image: postgres
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - /var/lib/postgresql/data/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - ./drawful
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db