services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: /home/gitlab-runner/builds/ZTttgQvU/0/team-projects-2022-23/team40-22/drawful
    command: python3 manage.py runserver 127.0.0.1:80
    volumes:
      - /home/gitlab-runner/builds/ZTttgQvU/0/team-projects-2022-23/team40-22/drawful
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db