version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn django_rest_cicd_pipeline.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - team40-22/.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - team40-22/.env.prod.db
  nginx:
    build: team40-22/nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: